FROM ubuntu

RUN apt-get update && apt-get install -y python-pip \
    curl \
    sudo \ 
    tcpdump \
    nano \ 
    vim

RUN pip install scapy

RUN curl https://raw.githubusercontent.com/Avielyo10/DNS-Amplification-Lab/master/scripts/base_script --output base_script

RUN chmod a+x base_script

