FROM ubuntu

RUN apt-get update && apt-get install -y python-pip \
    sudo \
    tcpdump 

RUN pip install scapy

ADD "scripts/sniffer" "sniffer"

RUN chmod a+x sniffer

ENTRYPOINT ["sudo","python","sniffer"]