FROM ubuntu

RUN apt-get update && apt-get install -y python-pip \
    curl \
    sudo \ 
    tcpdump \
    nano \ 
    vim

RUN pip install scapy

ADD "base_script" "base_script"

RUN chmod a+x base_script

