FROM ubuntu

RUN apt-get update && apt-get install -y python-pip \
    sudo \
    tcpdump \
    apache2 \
    apache2-utils \
    bmon

RUN pip install scapy

ADD "scripts/sniffer" "sniffer"

RUN chmod a+x sniffer

EXPOSE 80

ENTRYPOINT ["sudo","python","sniffer"]