FROM ubuntu

RUN apt-get update && apt-get install -y python-pip \
    curl \
    sudo \
    tcpdump 

RUN pip install scapy

RUN curl https://raw.githubusercontent.com/Avielyo10/DNS-Amplification-Lab/master/scripts/sniffer --output sniffer 

RUN chmod a+x sniffer

ENTRYPOINT ["sudo","python","sniffer"]